### PR TITLE
finish README

### PR DESCRIPTION
**Pull request by azhagananbu**

### CODE REVIEW

**Comment by azhagananbu** [comment]
nothing

**Comment by azhagananbu** [comment]
jkjkkj

**Comment by azhagananbu** [comment]
smalllogo

**Comment by azhagananbu** [comment]
smalllogocanary

**Comment by bot66** [comment]
I didn't subscribe,why always receive emails.

**Comment by smileytechguy** [comment]
What in the world is this pr?

**Comment by garrettw** [comment]
Spam

**Comment by yuric** [comment]
auto subscribed when using mobile app. Probably not necessary.

**Pull request closed without merging**
