### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by thedillonb**

### CODE REVIEW

**Comment by zacharylau10** [comment]
I am not part of your organization and remove me as well

发自我的 iPhone

在 2017年8月5日，09:25，Dillon Buchanan <notifications@github.com<mailto:notifications@github.com>> 写道：

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/thedillonb/CodeHub/pull/302

Commit Summary

  *   Fixed Improper Account Switching
  *   Upgrade SQLite Dependency
  *   Prevent Title Shift Due To Back Button
  *   Don't Show Branches If Only One Branch
  *   Bump Version List

File Changes

  *   M CodeHub.Core/CodeHub.Core.csproj<https://github.com/thedillonb/CodeHub/pull/302/files#diff-0> (30)
  *   M CodeHub.Core/ViewModels/Repositories/RepositoryViewModel.cs<https://github.com/thedillonb/CodeHub/pull/302/files#diff-1> (39)
  *   M CodeHub.Core/packages.config<https://github.com/thedillonb/CodeHub/pull/302/files#diff-2> (8)
  *   M CodeHub.iOS/CodeHub.iOS.csproj<https://github.com/thedillonb/CodeHub/pull/302/files#diff-3> (30)
  *   M CodeHub.iOS/Info.plist<https://github.com/thedillonb/CodeHub/pull/302/files#diff-4> (4)
  *   M CodeHub.iOS/ViewControllers/Accounts/AccountsViewController.cs<https://github.com/thedillonb/CodeHub/pull/302/files#diff-5> (5)
  *   M CodeHub.iOS/ViewControllers/TableViewController.cs<https://github.com/thedillonb/CodeHub/pull/302/files#diff-6> (2)
  *   M CodeHub.iOS/packages.config<https://github.com/thedillonb/CodeHub/pull/302/files#diff-7> (8)

Patch Links:

  *   https://github.com/thedillonb/CodeHub/pull/302.patch
  *   https://github.com/thedillonb/CodeHub/pull/302.diff

**Comment by wolfgangbaums** [comment]
Damn delete me!

**Comment by Denielliu** [comment]
I am not part of your organization and remove me as well 
发自我的 iPhone

> 在 2017年8月5日，11:31，wolfgangbaums <notifications@github.com> 写道：
> 
> I am not part of your organization and remove me as well

**Comment by aoshiden** [comment]
Me too please

**Comment by Hermann0703** [comment]
Me too please .


Hermann


On 8/5/2017 11:35，aoshiden<notifications@github.com> wrote：
Me too please

**Comment by achensid** [comment]
PLZ remove me as well.
在 2017年8月5日，上午11:35，aoshiden <notifications@github.com<mailto:notifications@github.com>> 写道：

Me too please

**Comment by XiongJiangong** [comment]
don't send email to me




发自网易邮箱大师
On 08/05/2017 11:37, Hermann wrote:


Me too please .


Hermann


On 8/5/2017 11:35，aoshiden<notifications@github.com> wrote：
Me too please

**Comment by dslftys** [comment]
me too.please。。

**Comment by Solidays1874h** [comment]
fuck you!!   Do not send me ffffffffffffucking email any more!!

**Comment by DelilahDell** [comment]
I would like to be removed too! Thank you!

**Comment by mbhuddleston** [comment]
Not to be rude sir/madam but you do realize you are cursing out an
automated system.  The programmer of this is not doing it the selection you
made to receive them is, therefore perhaps you are cursing yourself out??
Find the setting and change it or select these messages for immediate move
to spam.  Do not get stressed out.  The programmer may not have it checked
to receive these messages and that's why he hasn't done anything.

**Comment by thedillonb** [comment]
Again, for those of you that don't understand how GitHub works, you need to "unwatch" the repository to stop receiving emails. I can't unsubscribe you. If you continue to ask to be unsubscribed I will block you from this repository and all other repos I own as that is my only option if you continue to spam the project.

**Comment by alf3** [comment]
Unwatch what repository where?  All I did was download CodeHub on iOS. Give explicit  instruction on how to turn this off.

Random numbers are too important to be left to chance.

**Comment by Denielliu** [comment]
fuck you!! Do not send me ffffffffffffucking email any more!!
发自我的 iPhone

> 在 2017年8月5日，12:41，Solidays1874h <notifications@github.com> 写道：
> 
> fuck you!! Do not send me ffffffffffffucking email any more!!

**Comment by Sebachowa** [comment]
For the ones that doesnt want to receive notifications in every issue, you should click in unwatch and then in ignore or not watching.

**Comment by stonedreamforest** [comment]
@Denielliu You can choose not to watch  白痴 别出来丢人

**Comment by dige1993** [comment]
I am not part of your organization and remove me as well 

From my iPhone6s plus

**Comment by Denielliu** [comment]
你妈个逼，傻逼

发自我的 iPhone

**Comment by stonedreamforest** [comment]
@Denielliu get out 👎

**Comment by atticmanatee** [comment]
To all the idiots who don’t know what they’re doing and then complain to the Dev:

Go here: 
https://github.com/thedillonb/CodeHub

Click here:

**Comment by weguru** [comment]
I am not part of your organization and remove me as well

**Pull request merged**
